agents:
  queue: "macOS-Monterey-12-4"

steps:
  - command: echo user $${SAUCE_USERNAME} 
  - command: echo key $${SAUCE_ACCESS_KEY} 

  - command: "./scripts/create-example-application-archive.sh MuxPlayerSwiftExample"
    label: ":xcode: Export Test Application Archive"
    artifact_paths:
      - "./Examples/MuxPlayerSwiftExample/MuxPlayerSwiftExample.ipa"
      - "./Examples/MuxPlayerSwiftExample/Packaging.log"
      - "./Examples/MuxPlayerSwiftExample/DistributionSummary.plist"
  - wait
  - command: "buildkite-agent artifact download \"Examples/MuxPlayerSwiftExample/MuxPlayerSwiftExample.ipa\" \"$PWD\" && ./scripts/upload-example-application-to-sauce-labs.sh"
    label: ":saucelabs: Upload Test Application to Sauce Labs App Storage"
