agents:
  queue: "macOS-Monterey-12-4"

steps:
  - command: "./scripts/run-unit-tests.sh MuxPlayerSwift"
    label: ":xcode_simulator: Unit Test Pass"
  - wait
  - command: "./scripts/run-ui-tests.sh MuxPlayerSwiftExample"
    label: ":xcode_simulator: Baseline Unit Test Pass"
