apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
xcuitest:
  app: storage:386d543f-3ac4-414d-8690-9ed383f600e2

suites:
  - name: "example application xcuitest"
    testOptions:
      class:
        - MUXSDKStatsExampleSPMUITests.MUXSDKStatsExampleSPMUITests
    devices:
      - name: "iPhone 15"
        platformVersion: "18.0"
        options:
          carrierConnectivity: false
          deviceType: PHONE
          private: false
