apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
xcuitest:
  app: storage:5ee37f66-eaa1-40d8-b0e8-514ceb7ae123
  testApp:  storage:5ee37f66-eaa1-40d8-b0e8-514ceb7ae123

suites:
  - name: "example application xcuitest"
    testOptions:
      class:
        - MUXSDKStatsExampleSPMUITests.MUXSDKStatsExampleSPMUITests
    devices:
      - name: "iPhone 15"
        platformVersion: "18.0"
        options:
          carrierConnectivity: false
          deviceType: PHONE
          private: false
