apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
xcuitest:
  app: storage:MuxPlayerSwiftExample.ipa
  testApp: storage:MuxPlayerSwiftExample.ipa

suites:
  - name: "example application xcuitest"
    testOptions:
      class:
        - MUXSDKStatsExampleSPMUITests.MUXSDKStatsExampleSPMUITests
    devices:
      - name: "iPhone 15"
        platformVersion: "18.0"
        options:
          carrierConnectivity: false
          deviceType: PHONE
          private: false
