apiVersion: v1alpha
kind: xcuitest
xcuitest:
  app: ./Examples/MuxPlayerSwiftExample.ipa
  testApp: ./Examples/MuxPlayerSwiftExample.ipa

suites:
  - name: "example application xcuitest"
    testOptions:
      class:
        - MUXSDKStatsExampleSPMUITests.MUXSDKStatsExampleSPMUITests
    devices:
      - name: "iPhone 15"
        platformVersion: "18.0"
        options:
          carrierConnectivity: false
          deviceType: PHONE
          private: false
